export const banks = [
    {
        name: 'Сбербанк',
        cssclass: 'sber',
        image: '/assets/img/purchase/credit/sberb_logo_bage.svg',
        rate: '10%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Открытие',
        cssclass: 'open',
        image: '/assets/img/purchase/credit/open_logo.png',
        rate: '10%',
        date: '5',
        payment: '10',
        isNew: false
    }, {
        name: 'ВТБ',
        cssclass: 'vtb',
        image: '/assets/img/purchase/credit/vtb_logo_bage.svg',
        rate: '3%',
        date: '30',
        payment: '5',
        isNew: false
    }, {
        name: 'Росбанк дом',
        cssclass: 'rossBank',
        image: '/assets/img/purchase/credit/rossBank_logo.jpg',
        rate: '0%',
        date: '30',
        payment: '8',
        isNew: false
    }, {
        name: 'Возрождение Банк',
        cssclass: 'ress',
        image: '/assets/img/purchase/credit/ress_logo_bage.png',
        rate: '0%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'ТрансКапиталБанк',
        cssclass: 'capital',
        image: '/assets/img/purchase/credit/capital_logo_bage.svg',
        rate: '0%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'ПСБ',
        cssclass: 'psb',
        image: '/assets/img/purchase/credit/psb_logo_bage.svg',
        rate: '0%',
        date: '11',
        payment: '10',
        isNew: false
    }, {
        name: 'Абсолют Банк',
        cssclass: 'absolute',
        image: '/assets/img/purchase/credit/absolute_logo.jpg',
        rate: '0%',
        date: '30',
        payment: '2',
        isNew: false
    }, {
        name: 'Газпромбанк',
        cssclass: 'gasprom',
        image: '/assets/img/purchase/credit/gasprom_logo.jpg',
        rate: '0%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Россельхозбанк',
        cssclass: 'ross',
        image: '/assets/img/purchase/credit/ross_logo.svg',
        rate: '0%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Металлинвестбанк',
        cssclass: 'iron',
        image: '/assets/img/purchase/credit/iron_logo.svg',
        rate: '30%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'ДОМ РФ',
        cssclass: 'dom',
        image: '/assets/img/purchase/credit/dom_logo.svg',
        rate: '0%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Райффайзенбанк',
        cssclass: 'raif',
        image: '/assets/img/purchase/credit/raif_logo_bage.svg',
        rate: '8%',
        date: '30',
        payment: '7',
        isNew: false
    }, {
        name: 'Совкомбанк',
        cssclass: 'sovcom',
        image: '/assets/img/purchase/credit/sovcom_logo.png',
        rate: '7%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Уралсиб банк',
        cssclass: 'ural',
        image: '/assets/img/purchase/credit/ural_logo_bage.svg',
        rate: '0%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Банк Зенит',
        cssclass: 'zenit',
        image: '/assets/img/purchase/credit/zenit_logo_bage.svg',
        rate: '6%',
        date: '30',
        payment: '10',
        isNew: false
    }, {
        name: 'Банк Связь',
        cssclass: 'svazBank',
        image: '/assets/img/purchase/credit/svazBank_logo.png',
        rate: '0%',
        date: '30',
        payment: '8',
        isNew: false
    }
];
